# This file was generated by GoReleaser. DO NOT EDIT.
cask "toad" do
  name "toad"
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/scaler-tech/toad"
  version "0.1.78"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toad"

  on_macos do
    on_intel do
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_macOS_64bit.tar.gz"
      sha256 "00a7b9d1ced3ac0f2b8cbe3c52475fbfd36334ec6f7fd1efe6ef64defc2b8762"
    end
    on_arm do
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_macOS_ARM64.tar.gz"
      sha256 "26afe510bcc64e5e94fe7429fca24359b8ad7c347d6990d57b8635a9b0f8b27e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_Linux_64bit.tar.gz"
      sha256 "effb17dc71da67cf2a2f6a2331b383c42d92675870101283035c5ed3e14147b8"
    end
    on_arm do
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_Linux_ARM64.tar.gz"
      sha256 "3fb414db4b1d58d5f8b4a75f56162ffad8b44f720d5f9b54c5768bcb74225112"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toad"]
    end
  end

  caveats do
    "run 'toad --help' to get started"
  end

  # No zap stanza required
end
