# This file was generated by GoReleaser. DO NOT EDIT.
cask "toad" do
  version "0.2.13"

  on_macos do
    on_intel do
      sha256 "ca29a6adcfd817bfe516fbbdc3a6e65360e90578ed5ced16dcbd9731669c69e6"
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_macOS_64bit.tar.gz"
    end
    on_arm do
      sha256 "6304c178c99aef4aabfe6dfa004dbe6e8747d1ecd3766af1046b1af63199127f"
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_macOS_ARM64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9851db97225858626dd8d6184029511711f0f43450ca38b9e0e66437221fc70e"
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_Linux_64bit.tar.gz"
    end
    on_arm do
      sha256 "7a4a79cafc88d92ffb70bce8b978be4fc1b8f9e7189f2820d6a5e7ad1f4483d7"
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_Linux_ARM64.tar.gz"
    end
  end

  name "toad"
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/scaler-tech/toad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toad"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    run 'toad --help' to get started
  EOS
end
