# This file was generated by GoReleaser. DO NOT EDIT.
cask "toad" do
  name "toad"
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/scaler-tech/toad"
  version "0.1.118"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toad"

  on_macos do
    on_intel do
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_macOS_64bit.tar.gz"
      sha256 "83ad7776821cf3946406796ef2588b74ac5d33fa00333da5d42500d945a48e23"
    end
    on_arm do
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_macOS_ARM64.tar.gz"
      sha256 "04b0abe0f75e444f454818327eb94acdc052f67aa472f43b11d870d7d561f274"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_Linux_64bit.tar.gz"
      sha256 "00164f33e2ec74131b1f35cbe0f95d433b6137e5e9d43f4a5a531ac6b85294ca"
    end
    on_arm do
      url "https://github.com/scaler-tech/toad/releases/download/v#{version}/toad_v#{version}_Linux_ARM64.tar.gz"
      sha256 "9f6644e77372a7d82fad73152b85cff603b4ceb7a6532e0de4963231a4855a4d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toad"]
    end
  end

  caveats do
    "run 'toad --help' to get started"
  end

  # No zap stanza required
end
